'use client';

import Script from 'next/script';
import { useEffect, useRef, useState } from 'react';
import type {Layer,NetworkPoint} from './NetworkExperience';
import {NETWORK_COLORS} from './NetworkExperience';
import styles from './CesiumNetworkGlobe.module.css';

declare global{interface Window{Cesium?:any;CESIUM_BASE_URL?:string}}
type RegionFocus={lon:number;lat:number;height:number;nonce:number};
type Hover={x:number;y:number;title:string;detail:string}|null;
type Selection={type:Layer;lat:number;lon:number;nearby:number}|null;
type Country={name:string;polygons:number[][][][];boxes:[number,number,number,number][]};
type Props={points:readonly NetworkPoint[];layer:Layer;mode:'coordinates'|'aggregate'|'loading';focus?:RegionFocus;onExplore?:()=>void};
const BASE='https://cesium.com/downloads/cesiumjs/releases/1.143/Build/Cesium/',SOURCE=`${BASE}Cesium.js`,WIDGET_CSS=`${BASE}Widgets/widgets.css`,EARTH_RADIUS_KM=6371;
const LABELS:Record<Layer,string>={all:'All Providers',medical:'Medical / Occupational Health',dental:'Dental',laboratory:'Laboratory',imaging:'Imaging / Radiology',cardiology:'Cardiology',audiology:'Audiology / Hearing','drug-testing':'Drug Testing',pharmacy:'Pharmacy / Vaccination',diagnostic:'Other Diagnostics'};
if(typeof window!=='undefined')window.CESIUM_BASE_URL=BASE;

function nearbyCount(points:readonly NetworkPoint[],lat:number,lon:number){const toRad=Math.PI/180,lat1=lat*toRad;let count=0;for(const point of points){const dLat=(point.lat-lat)*toRad,dLon=(point.lon-lon)*toRad,lat2=point.lat*toRad,a=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLon/2)**2;if(2*EARTH_RADIUS_KM*Math.asin(Math.min(1,Math.sqrt(a)))<=100)count++}return count}
function contains(ring:number[][],lon:number,lat:number){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const [xi,yi]=ring[i],[xj,yj]=ring[j];if((yi>lat)!==(yj>lat)&&lon<(xj-xi)*(lat-yi)/(yj-yi)+xi)inside=!inside}return inside}
function parseCountries(payload:any):Country[]{return(payload.features??[]).map((feature:any)=>{const geometry=feature.geometry,polygons:number[][][][]=geometry?.type==='Polygon'?[geometry.coordinates]:geometry?.type==='MultiPolygon'?geometry.coordinates:[];return{name:feature.properties?.name??feature.id??'Unknown',polygons,boxes:polygons.map(poly=>{const ring=poly[0]??[],xs=ring.map(p=>p[0]),ys=ring.map(p=>p[1]);return[Math.min(...xs),Math.min(...ys),Math.max(...xs),Math.max(...ys)]})}}).filter((country:Country)=>country.polygons.length)}

export default function CesiumNetworkGlobe({points,layer,mode,focus,onExplore}:Props){
  const hostRef=useRef<HTMLDivElement|null>(null),viewerRef=useRef<any>(null),pointCollectionRef=useRef<any>(null),selectionCollectionRef=useRef<any>(null),boundaryEntitiesRef=useRef<any[]>([]),buildingsRef=useRef<any>(null),photorealRef=useRef<any>(null),interactionTimerRef=useRef<ReturnType<typeof setTimeout>|null>(null),autoRotateRef=useRef(true),pointsRef=useRef<readonly NetworkPoint[]>(points),modeRef=useRef(mode),selectionRef=useRef<Selection>(null),onExploreRef=useRef(onExplore);
  const[loaded,setLoaded]=useState(Boolean(typeof window!=='undefined'&&window.Cesium)),[ready,setReady]=useState(false),[error,setError]=useState(false),[hover,setHover]=useState<Hover>(null),[selection,setSelection]=useState<Selection>(null),[visibleCount,setVisibleCount]=useState(0),[countries,setCountries]=useState<Country[]>([]);const token=process.env.NEXT_PUBLIC_CESIUM_ION_TOKEN?.trim()||'';
  useEffect(()=>{pointsRef.current=points},[points]);useEffect(()=>{modeRef.current=mode},[mode]);useEffect(()=>{onExploreRef.current=onExplore},[onExplore]);
  useEffect(()=>{fetch('/data/network-countries.geojson',{cache:'force-cache'}).then(r=>r.ok?r.json():Promise.reject()).then(data=>setCountries(parseCountries(data))).catch(()=>setCountries([]))},[]);
  useEffect(()=>{if(document.querySelector('link[data-docbox-cesium]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href=WIDGET_CSS;link.dataset.docboxCesium='true';document.head.appendChild(link)},[]);
  useEffect(()=>{const Cesium=window.Cesium;if(!loaded||!Cesium||!hostRef.current||viewerRef.current)return;try{
    if(token)Cesium.Ion.defaultAccessToken=token;const viewer=new Cesium.Viewer(hostRef.current,{animation:false,timeline:false,geocoder:false,homeButton:false,baseLayerPicker:false,sceneModePicker:false,navigationHelpButton:false,fullscreenButton:false,infoBox:false,selectionIndicator:false,terrain:token?Cesium.Terrain.fromWorldTerrain({requestVertexNormals:true,requestWaterMask:true}):undefined});viewerRef.current=viewer;const scene=viewer.scene;
    scene.backgroundColor=Cesium.Color.fromCssColorString('#010509');scene.globe.baseColor=Cesium.Color.fromCssColorString('#031118');scene.globe.showGroundAtmosphere=true;scene.globe.enableLighting=true;scene.globe.depthTestAgainstTerrain=false;scene.globe.maximumScreenSpaceError=1.7;scene.skyAtmosphere.show=true;scene.skyAtmosphere.atmosphereLightIntensity=8;scene.highDynamicRange=true;scene.fog.enabled=true;scene.fog.density=.00016;scene.screenSpaceCameraController.minimumZoomDistance=90;scene.screenSpaceCameraController.maximumZoomDistance=28000000;scene.screenSpaceCameraController.enableCollisionDetection=true;viewer.camera.setView({destination:Cesium.Cartesian3.fromDegrees(-22,18,18500000),orientation:{heading:Cesium.Math.toRadians(8),pitch:Cesium.Math.toRadians(-72),roll:0}});
    pointCollectionRef.current=scene.primitives.add(new Cesium.PointPrimitiveCollection());selectionCollectionRef.current=scene.primitives.add(new Cesium.PointPrimitiveCollection());
    if(token&&typeof Cesium.createOsmBuildingsAsync==='function')Cesium.createOsmBuildingsAsync().then((tileset:any)=>{if(!viewer.isDestroyed())buildingsRef.current=scene.primitives.add(tileset)}).catch(()=>{});
    if(token&&typeof Cesium.createGooglePhotorealistic3DTileset==='function')Cesium.createGooglePhotorealistic3DTileset().then((tileset:any)=>{if(!viewer.isDestroyed()){photorealRef.current=scene.primitives.add(tileset);if(buildingsRef.current)buildingsRef.current.show=false}}).catch(()=>{});
    const handler=new Cesium.ScreenSpaceEventHandler(scene.canvas),pause=()=>{onExploreRef.current?.();autoRotateRef.current=false;if(interactionTimerRef.current)clearTimeout(interactionTimerRef.current);interactionTimerRef.current=setTimeout(()=>{if(!selectionRef.current)autoRotateRef.current=true},6500)};
    handler.setInputAction((movement:any)=>{const picked=scene.pick(movement.endPosition),meta=picked?.id?.__docboxMeta??picked?.id??picked?.primitive?.id;if(!meta){setHover(null);return}if(meta.kind==='country')setHover({x:movement.endPosition.x,y:movement.endPosition.y,title:String(meta.name).toUpperCase(),detail:`${meta.label} · ${meta.count.toLocaleString()} mapped location${meta.count===1?'':'s'}`});else if(meta.kind==='provider')setHover({x:movement.endPosition.x,y:movement.endPosition.y,title:`${LABELS[meta.type as Layer]} node`,detail:`${meta.lat.toFixed(2)}°, ${meta.lon.toFixed(2)}°${meta.count?` · ${meta.count.toLocaleString()} records`:''}`});else setHover(null)},Cesium.ScreenSpaceEventType.MOUSE_MOVE);
    handler.setInputAction(()=>pause(),Cesium.ScreenSpaceEventType.LEFT_DOWN);handler.setInputAction(()=>pause(),Cesium.ScreenSpaceEventType.WHEEL);
    handler.setInputAction((movement:any)=>{const picked=scene.pick(movement.position),meta=picked?.id?.__docboxMeta??picked?.id??picked?.primitive?.id;if(!meta)return;if(meta.kind==='country'){pause();viewer.camera.flyTo({destination:Cesium.Cartesian3.fromDegrees(meta.lon,meta.lat,1700000),orientation:{heading:viewer.camera.heading+Cesium.Math.toRadians(18),pitch:Cesium.Math.toRadians(-58),roll:0},duration:2.2,easingFunction:Cesium.EasingFunction.QUINTIC_IN_OUT});return}if(meta.kind!=='provider')return;
      pause();autoRotateRef.current=false;setHover(null);const type=meta.type as Layer,nearby=nearbyCount(pointsRef.current,meta.lat,meta.lon),next={type,lat:meta.lat,lon:meta.lon,nearby};selectionRef.current=next;setSelection(next);selectionCollectionRef.current.removeAll();const position=Cesium.Cartesian3.fromDegrees(meta.lon,meta.lat,modeRef.current==='aggregate'?19000:5600),color=Cesium.Color.fromCssColorString(NETWORK_COLORS[type]);selectionCollectionRef.current.add({position,pixelSize:20,color:color.withAlpha(.2),outlineColor:color.withAlpha(.96),outlineWidth:2,disableDepthTestDistance:Number.POSITIVE_INFINITY});selectionCollectionRef.current.add({position,pixelSize:7,color:Cesium.Color.WHITE,outlineColor:color,outlineWidth:2,disableDepthTestDistance:Number.POSITIVE_INFINITY});viewer.camera.flyTo({destination:Cesium.Cartesian3.fromDegrees(meta.lon,meta.lat,900000),orientation:{heading:viewer.camera.heading+Cesium.Math.toRadians(22),pitch:Cesium.Math.toRadians(-58),roll:Cesium.Math.toRadians(1)},duration:1.4,easingFunction:Cesium.EasingFunction.QUINTIC_IN_OUT,complete:()=>viewer.camera.flyTo({destination:Cesium.Cartesian3.fromDegrees(meta.lon,meta.lat,18000),orientation:{heading:viewer.camera.heading+Cesium.Math.toRadians(20),pitch:Cesium.Math.toRadians(-28),roll:0},duration:2.1,easingFunction:Cesium.EasingFunction.QUINTIC_IN_OUT})})
    },Cesium.ScreenSpaceEventType.LEFT_CLICK);
    const tick=()=>{const height=viewer.camera.positionCartographic.height;if(autoRotateRef.current&&height>7200000&&!viewer.camera._currentFlight)viewer.camera.rotate(Cesium.Cartesian3.UNIT_Z,-.000055);const close=height<650000;if(buildingsRef.current)buildingsRef.current.show=close&&!photorealRef.current;if(photorealRef.current)photorealRef.current.show=close};viewer.clock.onTick.addEventListener(tick);setReady(true);setError(false);
    (viewer as any).__returnOrbit=()=>{const previous=selectionRef.current;selectionRef.current=null;selectionCollectionRef.current?.removeAll();setSelection(null);viewer.camera.flyTo({destination:Cesium.Cartesian3.fromDegrees(previous?.lon??-18,previous?.lat??18,2200000),orientation:{heading:viewer.camera.heading,pitch:Cesium.Math.toRadians(-62),roll:0},duration:1.7,easingFunction:Cesium.EasingFunction.CUBIC_IN_OUT,complete:()=>{autoRotateRef.current=true}})};
    return()=>{if(interactionTimerRef.current)clearTimeout(interactionTimerRef.current);handler.destroy();viewer.clock.onTick.removeEventListener(tick);if(!viewer.isDestroyed())viewer.destroy();viewerRef.current=null;pointCollectionRef.current=null;selectionCollectionRef.current=null;boundaryEntitiesRef.current=[]}
  }catch{setError(true);setReady(false)}},[loaded,token]);
  useEffect(()=>{const collection=pointCollectionRef.current,Cesium=window.Cesium;if(!ready||!collection||!Cesium)return;collection.removeAll();for(const point of points){const aggregate=mode==='aggregate',size=aggregate?Math.min(16,6+Math.log10((point.count??1)+1)*2):4.8,color=Cesium.Color.fromCssColorString(NETWORK_COLORS[point.type]);collection.add({position:Cesium.Cartesian3.fromDegrees(point.lon,point.lat,aggregate?18000:5200),pixelSize:size,color:color.withAlpha(aggregate?.98:.9),outlineColor:Cesium.Color.fromCssColorString('#f0feff').withAlpha(.32),outlineWidth:aggregate?1.6:.75,scaleByDistance:new Cesium.NearFarScalar(200000,1.9,22000000,.56),translucencyByDistance:new Cesium.NearFarScalar(100000,1,26000000,.58),disableDepthTestDistance:2200000,id:{kind:'provider',type:point.type,lat:point.lat,lon:point.lon,count:point.count??0}})}},[mode,points,ready]);
  useEffect(()=>{const collection=pointCollectionRef.current;if(!ready||!collection)return;let count=0;for(let i=0;i<collection.length;i++){const primitive=collection.get(i),show=layer==='all'||primitive.id?.type===layer;primitive.show=show;if(show)count+=primitive.id?.count||1}setVisibleCount(count);setHover(null)},[layer,mode,points,ready]);
  useEffect(()=>{const viewer=viewerRef.current,Cesium=window.Cesium;if(!ready||!viewer||!Cesium||!countries.length)return;for(const entity of boundaryEntitiesRef.current)viewer.entities.remove(entity);boundaryEntitiesRef.current=[];const selected=points.filter(point=>layer==='all'||point.type===layer),counts=new Map<Country,number>();for(const point of selected){for(const country of countries){let hit=false;for(let i=0;i<country.polygons.length;i++){const box=country.boxes[i];if(point.lon>=box[0]&&point.lon<=box[2]&&point.lat>=box[1]&&point.lat<=box[3]&&contains(country.polygons[i][0],point.lon,point.lat)){hit=true;break}}if(hit){counts.set(country,(counts.get(country)??0)+(point.count??1));break}}}const max=Math.max(1,...counts.values()),color=Cesium.Color.fromCssColorString(NETWORK_COLORS[layer]);for(const[country,count]of counts){const intensity=Math.log1p(count)/Math.log1p(max),box=country.boxes[0],meta={kind:'country',name:country.name,count,label:LABELS[layer],lon:(box[0]+box[2])/2,lat:(box[1]+box[3])/2};for(const polygon of country.polygons){const positions=Cesium.Cartesian3.fromDegreesArray(polygon[0].flat()),distance=new Cesium.DistanceDisplayCondition(0,10500000),halo=viewer.entities.add({polyline:{positions,width:7+intensity*9,material:color.withAlpha(.035+intensity*.1),clampToGround:true,distanceDisplayCondition:distance}}),core=viewer.entities.add({polyline:{positions,width:1.1+intensity*2.2,material:color.withAlpha(.32+intensity*.5),clampToGround:true,distanceDisplayCondition:distance}});halo.__docboxMeta=meta;core.__docboxMeta=meta;boundaryEntitiesRef.current.push(halo,core)}}return()=>{for(const entity of boundaryEntitiesRef.current)viewer.entities.remove(entity);boundaryEntitiesRef.current=[]}},[countries,layer,points,ready]);
  useEffect(()=>{const viewer=viewerRef.current,Cesium=window.Cesium;if(!ready||!viewer||!Cesium||!focus)return;autoRotateRef.current=false;selectionRef.current=null;selectionCollectionRef.current?.removeAll();setSelection(null);setHover(null);viewer.camera.flyTo({destination:Cesium.Cartesian3.fromDegrees(focus.lon,focus.lat,focus.height),orientation:{heading:Cesium.Math.toRadians(focus.lon*.035),pitch:Cesium.Math.toRadians(focus.height>12000000?-72:-60),roll:0},duration:2.15,easingFunction:Cesium.EasingFunction.QUINTIC_IN_OUT,complete:()=>{autoRotateRef.current=true}})},[focus,ready]);
  return <div className={styles.root} data-selected={selection?'true':'false'}><Script src={SOURCE} strategy="afterInteractive" onLoad={()=>setLoaded(true)} onError={()=>setError(true)}/><div ref={hostRef} className={styles.cesium} aria-label="Interactive 3D globe of anonymized Occu-Med provider locations"/><div className={styles.orbitGuide} aria-hidden="true"><i/><i/><span>GLOBAL NETWORK / LIVE ORBIT</span></div><div className={styles.vignette} aria-hidden="true"/>{!ready&&!error&&<div className={styles.loading}><i/><span>INITIALIZING GLOBAL NETWORK</span></div>}{error&&<div className={styles.error}><b>3D globe unavailable</b><span>Reload to retry the Cesium scene.</span></div>}{hover&&!selection&&<div className={styles.tooltip} style={{left:hover.x,top:hover.y}}><b>{hover.title}</b><small>{hover.detail}</small></div>}{selection&&<aside className={styles.selection}><span>NODE LOCK / ANONYMIZED</span><h2>{LABELS[selection.type]}</h2><div className={styles.coordinates}><b>{selection.lat.toFixed(3)}°</b><small>LATITUDE</small><b>{selection.lon.toFixed(3)}°</b><small>LONGITUDE</small></div><div className={styles.proximity}><b>{selection.nearby.toLocaleString()}</b><span>network nodes within ~100 km</span></div><button type="button" onClick={()=>(viewerRef.current as any)?.__returnOrbit?.()}>Return to regional orbit</button></aside>}<div className={styles.status}><span>{token?'ION TERRAIN / IMMERSIVE 3D':'CESIUMJS / GLOBAL NETWORK'}</span><b>{visibleCount.toLocaleString()}</b><small>VISIBLE NODES</small></div></div>;
}
