'use client';

import { useState } from 'react';
import styles from './ProviderFAQ.module.css';

const ITEMS = [
  {
    question: 'Does the provider make the employment or deployment decision?',
    answer: 'No. The provider performs the authorized evaluation, documents findings, and returns the requested records. Occu-Med’s medical review process interprets the completed information against the applicable job or program requirements.',
  },
  {
    question: 'What arrives with a referral?',
    answer: 'The referral identifies the authorized services and includes the forms, exam packet, or other case-specific material needed for the appointment. Occu-Med coordinates the requested scope so the facility knows what should be completed before the examinee arrives.',
  },
  {
    question: 'What should the facility return after the visit?',
    answer: 'Return the completed requested documentation and the supporting results generated by the authorized services — for example reports, tracings, images, laboratory results, or other requested records. Provider Relations follows the case when an item is missing or incomplete.',
  },
  {
    question: 'How are additional services handled?',
    answer: 'The fee schedule applies to authorized referrals. If something outside the authorized scope appears necessary, the facility should route that question back through Occu-Med rather than expanding the visit on its own.',
  },
  {
    question: 'How does payment work?',
    answer: 'The onboarding workflow is built around direct self-pay provider rates and post-service invoicing. The working agreement in this experience uses NET 30 terms for authorized services under the agreed fee schedule.',
  },
  {
    question: 'Can one organization enroll multiple locations?',
    answer: 'Yes. Locations can share one fee schedule or maintain location-specific rates. The agreement workspace keeps each physical address attached to the applicable services and pricing.',
  },
] as const;

export default function ProviderFAQ() {
  const [active, setActive] = useState(0);

  return (
    <section className={styles.faq} aria-labelledby="provider-faq-title">
      <div className={styles.lead}>
        <span>BEFORE YOU FINISH</span>
        <h2 id="provider-faq-title">The relationship should be<br /><em>easy to understand.</em></h2>
        <p>
          Occu-Med coordinates the referral and medical-review workflow. The provider&apos;s role stays focused:
          perform the authorized service, document it well, return the requested records, and invoice the agreed rate.
        </p>
      </div>

      <div className={styles.index}>
        {ITEMS.map((item, index) => (
          <button
            key={item.question}
            type="button"
            className={index === active ? styles.active : ''}
            onClick={() => setActive(index)}
            aria-expanded={index === active}
          >
            <span>{String(index + 1).padStart(2, '0')}</span>
            <strong>{item.question}</strong>
            <i>{index === active ? '−' : '+'}</i>
          </button>
        ))}
      </div>

      <div className={styles.answer} aria-live="polite">
        <span>ANSWER / {String(active + 1).padStart(2, '0')}</span>
        <p>{ITEMS[active].answer}</p>
      </div>
    </section>
  );
}
