export type StoryMode='hero'|'split'|'method'|'referral'|'services'|'report'|'result'|'workforce'|'deployment'|'network'|'values';
export type StoryScene={chapter:string;title:string;body:string;images:readonly string[];mode:StoryMode;fact:string;factLabel:string;caption:string;scrollVh:number};

// Canonical source: Story/Occu-Med_Company_Story.docx and
// Story/Occu-Med_PowerPoint_Complete_Text_Extraction.docx.
// Image order mirrors the user-authored public/photos sequence and must not be reordered.
export const STORY:readonly StoryScene[]=[
{chapter:'01 / ORIGIN',title:'The job changed the question.',body:'California-funded research led by attorney Jim A. Johnson connected pre-existing medical conditions with workplace injury risk. In 1979, Johnson and Dr. Devonna M. Kaji founded Occu-Med in Honolulu around a new premise: medical evidence only becomes useful when it is understood against the work a person must perform.',images:['Founders.png','Founders copy.png','California - Hawaii Map.png'],mode:'hero',fact:'1979',factLabel:'Honolulu / founded',caption:'Medical evidence + actual job demands.',scrollVh:230},
{chapter:'02 / THE PROBLEM',title:'A physical alone was not enough.',body:'The research showed that 41% of workplace injuries occur during an employee’s first year. Generic examinations could describe a person’s health, but they could not answer whether the findings mattered for a specific job.',images:['Concerned provider.png'],mode:'split',fact:'41%',factLabel:'first-year injuries',caption:'Healthy and job-ready are not the same question.',scrollVh:175},
{chapter:'03 / THE METHOD',title:'Put the job back into medicine.',body:'Occu-Med built a compatibility model around valid job information, a job-related medical examination, and expert review. That framework has been applied across more than 500 job classes, translating clinical findings into job-relevant decisions.',images:['EMPLOYEE ID.png','Diverse Healthcare Team Portrait (1).png'],mode:'method',fact:'500+',factLabel:'job classes',caption:'JOB + EXAM + COMPATIBILITY',scrollVh:205},
{chapter:'04 / REFERRAL',title:'One referral starts the chain.',body:'A referral is received. Scheduling confirms the examinee’s availability, contacts the clinic, confirms the appointment, and sends the authorization and exam packet. If the appointment is missed, the scheduling process starts again.',images:['Friendly Medical Appointment Call.png'],mode:'referral',fact:'01',factLabel:'authorized referral',caption:'Referral → availability → clinic → appointment → exam packet.',scrollVh:175},
{chapter:'05 / CLINICAL SERVICES',title:'Only what was authorized.',body:'The clinic performs the exact authorized scope—physical examination, laboratory collection, dental evaluation, audiometry, vaccination, or other requested services. The provider documents findings; Occu-Med controls the authorized scope and the downstream review.',images:['Medical Eval.png','Calm Clinic Blood Draw (1).png','Dental Eval.png','Audiometry.png','Pharmacist Administering a Vaccine(1) (1).png'],mode:'services',fact:'05',factLabel:'clinical disciplines',caption:'No added services outside the authorization.',scrollVh:270},
{chapter:'06 / DOCUMENTATION',title:'The exam is not finished when the patient leaves.',body:'Provider Relations confirms attendance and follows the clinic until the records are returned. EXAMQA reviews the documentation for completeness and accuracy, sends missing or incorrect items back for clinic correction, and performs final QA when the corrected packet returns.',images:['EXAM REPORT.png'],mode:'report',fact:'QA',factLabel:'initial → correction → final',caption:'Complete. Legible. Correct. Returned.',scrollVh:185},
{chapter:'07 / DETERMINATION',title:'Findings become a job-related outcome.',body:'Medical Review applies industry standards, legal guidance, job requirements, and the examination findings to the case. The typical determination target is 24–48 hours. The provider documents the findings; Occu-Med Medical Review issues the recommendation.',images:['Fitness Determination.png'],mode:'result',fact:'24–48',factLabel:'typical review hours',caption:'The employer receives the outcome—not confidential medical detail.',scrollVh:195},
{chapter:'08 / THE WORK',title:'Different work creates different medical questions.',body:'Public safety, construction, energy, education, government, healthcare, and other workforces carry different physical and regulatory demands. Occu-Med has served more than 500 public-safety clients while keeping the actual job at the center of the medical question.',images:['Diverse Workforce.png','Diverse Workforce2.png'],mode:'workforce',fact:'500+',factLabel:'public-safety clients',caption:'The job—not a generic physical—is the reference point.',scrollVh:210},
{chapter:'09 / DEPLOYMENT',title:'Readiness crosses borders.',body:'Deployment medicine adds destination standards, medical clearances, immunization schedules, certification requirements, and time-sensitive documentation. Occu-Med’s operating footprint has extended across more than 50 countries.',images:['International Certification.png','Vaccine Schedule.png'],mode:'deployment',fact:'50+',factLabel:'countries',caption:'Standards travel with the assignment.',scrollVh:205},
{chapter:'10 / THE NETWORK',title:'A global system needs somewhere to land.',body:'Occu-Med has supported more than one million employees through a medical and dental network documented at more than 15,000 locations. The current anonymized provider directory contains 23,524 valid mapped coordinates.',images:['Facilities.png','International Network.png'],mode:'network',fact:'23,524',factLabel:'current mapped coordinates',caption:'One operating model across a global provider footprint.',scrollVh:225},
{chapter:'11 / VALUES',title:'The system ends where the culture begins.',body:'Humility. Positivity. Customer service. Quality. Integrity. Diligence. Six core values define how the work moves from the first referral to the final determination.',images:['Corevalue.png','Corevalue2.png','Corevalue3.png','Corevalue4.png','Corevalue5.png','Corevalue6.png'],mode:'values',fact:'06',factLabel:'core values',caption:'The operating model is only as strong as the way it is carried out.',scrollVh:245},
];

export const PORTALS=[
{id:'history',href:'/experience/history',number:'01',title:'History & Evolution',note:'1979 to today · people, moments and milestones',tone:'gold'},
{id:'network',href:'/experience/network',number:'02',title:'Explore the network',note:'23,524 anonymized mapped facilities',tone:'cyan'},
{id:'resources',href:'/experience/resources',number:'03',title:'Provider resources',note:'Guidance organized around your specialty',tone:'violet'},
{id:'questions',href:'/experience/questions',number:'04',title:'Provider Q&A',note:'Clear answers before the first referral',tone:'blue'},
{id:'agreement',href:'/experience/agreement',number:'05',title:'Service agreement',note:'Build and submit your pricing proposal',tone:'white'},
] as const;
